# Converted JSON -> TOML

[trust]
trust_anchors = '''-----BEGIN CERTIFICATE-----
MIIF5DCCA8ygAwIBAgIQIirlcpCVi5BClPXKKwZLpTANBgkqhkiG9w0BAQwFADCB
gjELMAkGA1UEBhMCVVMxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjFT
MFEGA1UEAxNKTWljcm9zb2Z0IEVudGVycHJpc2UgSWRlbnRpdHkgVmVyaWZpY2F0
aW9uIFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IDIwMjAwHhcNMjAwNDE2MTkw
MzA5WhcNNDUwNDE2MTkxMTQ0WjCBgjELMAkGA1UEBhMCVVMxHjAcBgNVBAoTFU1p
Y3Jvc29mdCBDb3Jwb3JhdGlvbjFTMFEGA1UEAxNKTWljcm9zb2Z0IEVudGVycHJp
c2UgSWRlbnRpdHkgVmVyaWZpY2F0aW9uIFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9y
aXR5IDIwMjAwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCiIAgEj9/b
zhv00hRK9rg4cLkpIm/hGXIFqX0F0QGaigjsg6f26UQMNCDghvRqcL1DhDqW2UQ8
fbfIwMm11EHeWffGOoMjFqhFFpIsKJs/NtIHTjY5mUM+YFVa4pWB6BeaV1lSxxGT
4tFojm5F0R1hnHhfA3Km4fOyjVkrrOxCCMN0eHifN5k4R7COqOPLi88SWzbayJ+Y
h6YCbYV1uoJvIt76+am8fhCSxLMT6X1l2IjlxUOrhCeNjSgbKhhkT1QdezVz+zki
oPbwMuFJ+4II8KcHmhxCRKE2VhWoZP0abVJDNXfdHBNtR6pF0TUfylcTstBx5m6L
qynxdqome49oBCmSH9epyQyOck5ZL1Eb4sbsFeowEX2SSX57Rx8b6klpNSMGoVK8
vnt7DrzoIwWMw/AlGYsqghjiCevA9LnKTIYFJgJCvTpnKtIlCqZgb5VSZ/AJI+NX
xqth4pS/mBlSTFuo/O5jblWKA7jJa53Y8qmMlCeWQs5tgmePu8Gc1h3A5vUVuE/y
gA0ThIUs6pknnl48/s0Trw6kfepHSBXYFzhb4CsF8+aqTT+QyZfei5buDb4/Qfw8
nhbVC4F77f+V6gj3Fi2pHV5jyddsNc9TxOC2KySagYIr5irD1bg2VoSCy41naSAA
ohQzP75gSP24y04I36aEFd0eA2qKdaRN2QIDAQABo1QwUjAOBgNVHQ8BAf8EBAMC
AYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUfwR9gDEMAknsRrTdomc36lmw
zgYwEAYJKwYBBAGCNxUBBAMCAQAwDQYJKoZIhvcNAQEMBQADggIBAEJhzDfNF6Qf
WRggo7r7aCGcsgbfq+4d1G1JUTDI8i5FOOTRbS7FUDmYm8mxyN75U0aXKUkDBna1
q7YUavJk9bFdFwRTGd4BQq5lEMrqO9SASHIIpo/qEZrgzfdDKvYD1xj+pRA/JchV
WbpU1j5q2LE1RHcqwDC5zkIWhpNSuN8nU1w4+90cdxEMJthwVI4k437LAtSoPZrt
h+1fxxwIxMI/o4y0OFBFQukse4d2RWHxa1qTcRgm9ZMBM0XFHQIu/vD21Scvz/3Z
86/oy8yJVAZMiuHWWx4VjHOZr222Bfm837Td1AUA5l/pUCEAMTEVfFhKfLe5AVAu
KRrrbyvvmkWlplXwyPvjFujv3N9uwHLGHLLKjrT4hn0AxiJ0otMew+sV88dFombZ
wIwiwrWjZiyIxjssmdZ/jhMNurlJC4ajbEHJZiSGnlKpJjbuJxCujbffrj+1tiKZ
xJZPlFUCrtoxN21og1yYAfm01hi+uZ3QChxaUBNhcTVgcxqxaFTCMknTvRACbrXW
8VGl81Vn8G9cCbe+LYaimWViNKCx0k2wBkCiBRwMLGh7tCnvcqaq1mabyTJt7J4G
sibkXZHC26Ifyx+XNagOoQaIhY4k/co/l+5FFJGpZOcfcMnqnJOABDCXPYlerBZ6
FeDDrKZ8pK5TdlXx7RRRfS93s+US9iut
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIGtDCCBJygAwIBAgIQDcesVwX/IZkuQEMiDDpJhjANBgkqhkiG9w0BAQsFADBi
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMSEwHwYDVQQDExhEaWdpQ2VydCBUcnVzdGVkIFJvb3Qg
RzQwHhcNMjUwNTA3MDAwMDAwWhcNMzgwMTE0MjM1OTU5WjBpMQswCQYDVQQGEwJV
UzEXMBUGA1UEChMORGlnaUNlcnQsIEluYy4xQTA/BgNVBAMTOERpZ2lDZXJ0IFRy
dXN0ZWQgRzQgVGltZVN0YW1waW5nIFJTQTQwOTYgU0hBMjU2IDIwMjUgQ0ExMIIC
IjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAtHgx0wqYQXK+PEbAHKx126NG
aHS0URedTa2NDZS1mZaDLFTtQ2oRjzUXMmxCqvkbsDpz4aH+qbxeLho8I6jY3xL1
IusLopuW2qftJYJaDNs1+JH7Z+QdSKWM06qchUP+AbdJgMQB3h2DZ0Mal5kYp77j
YMVQXSZH++0trj6Ao+xh/AS7sQRuQL37QXbDhAktVJMQbzIBHYJBYgzWIjk8eDrY
hXDEpKk7RdoX0M980EpLtlrNyHw0Xm+nt5pnYJU3Gmq6bNMI1I7Gb5IBZK4ivbVC
iZv7PNBYqHEpNVWC2ZQ8BbfnFRQVESYOszFI2Wv82wnJRfN20VRS3hpLgIR4hjzL
0hpoYGk81coWJ+KdPvMvaB0WkE/2qHxJ0ucS638ZxqU14lDnki7CcoKCz6eum5A1
9WZQHkqUJfdkDjHkccpL6uoG8pbF0LJAQQZxst7VvwDDjAmSFTUms+wV/FbWBqi7
fTJnjq3hj0XbQcd8hjj/q8d6ylgxCZSKi17yVp2NL+cnT6Toy+rN+nM8M7LnLqCr
O2JP3oW//1sfuZDKiDEb1AQ8es9Xr/u6bDTnYCTKIsDq1BtmXUqEG1NqzJKS4kOm
xkYp2WyODi7vQTCBZtVFJfVZ3j7OgWmnhFr4yUozZtqgPrHRVHhGNKlYzyjlroPx
ul+bgIspzOwbtmsgY1MCAwEAAaOCAV0wggFZMBIGA1UdEwEB/wQIMAYBAf8CAQAw
HQYDVR0OBBYEFO9vU0rp5AZ8esrikFb2L9RJ7MtOMB8GA1UdIwQYMBaAFOzX44LS
cV1kTN8uZz/nupiuHA9PMA4GA1UdDwEB/wQEAwIBhjATBgNVHSUEDDAKBggrBgEF
BQcDCDB3BggrBgEFBQcBAQRrMGkwJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRp
Z2ljZXJ0LmNvbTBBBggrBgEFBQcwAoY1aHR0cDovL2NhY2VydHMuZGlnaWNlcnQu
Y29tL0RpZ2lDZXJ0VHJ1c3RlZFJvb3RHNC5jcnQwQwYDVR0fBDwwOjA4oDagNIYy
aHR0cDovL2NybDMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0VHJ1c3RlZFJvb3RHNC5j
cmwwIAYDVR0gBBkwFzAIBgZngQwBBAIwCwYJYIZIAYb9bAcBMA0GCSqGSIb3DQEB
CwUAA4ICAQAXzvsWgBz+Bz0RdnEwvb4LyLU0pn/N0IfFiBowf0/Dm1wGc/Do7oVM
Y2mhXZXjDNJQa8j00DNqhCT3t+s8G0iP5kvN2n7Jd2E4/iEIUBO41P5F448rSYJ5
9Ib61eoalhnd6ywFLerycvZTAz40y8S4F3/a+Z1jEMK/DMm/axFSgoR8n6c3nuZB
9BfBwAQYK9FHaoq2e26MHvVY9gCDA/JYsq7pGdogP8HRtrYfctSLANEBfHU16r3J
05qX3kId+ZOczgj5kjatVB+NdADVZKON/gnZruMvNYY2o1f4MXRJDMdTSlOLh0HC
n2cQLwQCqjFbqrXuvTPSegOOzr4EWj7PtspIHBldNE2K9i697cvaiIo2p61Ed2p8
xMJb82Yosn0z4y25xUbI7GIN/TpVfHIqQ6Ku/qjTY6hc3hsXMrS+U0yy+GWqAXam
4ToWd2UQ1KYT70kZjE4YtL8Pbzg0c1ugMZyZZd/BdHLiRu7hAWE6bTEm4XYRkA6T
l4KSFLFk43esaUeqGkH/wyW4N7OigizwJWeukcyIPbAvjSabnf7+Pu0VrFgoiovR
Diyx3zEdmcif/sYQsfch28bZeUz2rtY/9TCA6TD8dC3JE3rYkrhLULy7Dc90G6e8
BlqmyIjlgp2+VqsS9/wQD7yFylIz0scmbKvFoW2jNrbM1pD2T7m3XA==
-----END CERTIFICATE-----'''

trust_config = '''//id-kp-emailProtection 
1.3.6.1.5.5.7.3.4
//id-kp-documentSigning 
1.3.6.1.5.5.7.3.36
//id-kp-timeStamping 
1.3.6.1.5.5.7.3.8
//id-kp-OCSPSigning 
1.3.6.1.5.5.7.3.9
// MS C2PA Signing
1.3.6.1.4.1.311.76.59.1.9
1.2.840.113583.1.1.7
// MS Timestamping
1.3.6.1.4.1.311.97.1.3.1.29433.35007.34545.16815.37291.11644.53265.56135
// Signer Specific EKUs
1.3.6.1.4.1.311.97.1.3.1.29433.35007.34545.16815.37291.11644.53265.56135'''

[verify]
verify_after_reading = true
verify_after_sign = true
verify_trust = true
verify_timestamp_trust = true
ocsp_fetch = false
remote_manifest_fetch = true
check_ingredient_trust = true
skip_ingredient_conflict_resolution = false
strict_v1_validation = false

[builder.thumbnail]
enabled = true
ignore_errors = true
long_edge = 1024
prefer_smallest_format = true
quality = "Medium"

[builder.actions.auto_created_action]
enabled = true
source_type = "Empty"

[builder.actions.auto_opened_action]
enabled = true

[builder.actions.auto_placed_action]
enabled = true

[builder.actions]
all_actions_included = true

[core]
debug = false
salt_jumbf_boxes = true
prefer_box_hash = false
compress_manifest = true

version_major = 1
version_minor = 0